apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: devops-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: lovelord88/auth:latest
          ports:
            - containerPort: 3000
