apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: devops-apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: myapp.local
      http:
        paths:
          - path: /auth/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 3000
          - path: /products/?(.*)
            pathType: Prefix
            backend:
              service:
                name: products
                port:
                  number: 3001
          - path: /orders/?(.*)
            pathType: Prefix
            backend:
              service:
                name: orders
                port:
                  number: 3002
