# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: microservices-ingress
#   namespace: devops-apps
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
# spec:
#   rules:
#     - host: myapp.local
#       http:
#         paths:
#           - path: /auth/?(.*)
#             pathType: Prefix
#             backend:
#               service:
#                 name: auth
#                 port:
#                   number: 80
#           - path: /products/?(.*)
#             pathType: Prefix
#             backend:
#               service:
#                 name: products
#                 port:
#                   number: 80
#           - path: /orders/?(.*)
#             pathType: Prefix
#             backend:
#               service:
#                 name: orders
#                 port:
#                   number: 80

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: devops-apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: auth.myapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 80

    - host: products.myapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: products
                port:
                  number: 80

    - host: orders.myapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orders
                port:
                  number: 80
