apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: devops-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: lovelord88/products:latest
          ports:
            - containerPort: 3001