apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: devops-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: lovelord88/orders:latest
          ports:
            - containerPort: 3002